name: UltimateKingdoms
version: '${project.version}'
main: me.sirimperivm.spigot.Main
api-version: '1.20'
loadbefore:
  - WorldGuard
softdepend:
  - PlaceholderAPI
  - WorldGuard

commands:
  kg:
    aliases:
      - kingdoms
  kga:
    aliases:
      - kingdomsadmin
