storage:
  type: sqlite
  credentials:
    host: "127.0.0.1"
    port: 3306
    username: "ultimatekingdoms"
    password: "ultimatekingdoms"
    dbname: "ultimatekingdoms"
    options: ""

other:
  strings:
    number-formatter:
      associations:
        - "1000.0-k"
        - "1000000.0-M"
        - "1000000000.0-B"
        - "1000000000000.0-T"
        - "1000000000000000.0-Q"
      format-size: 5

kingdoms:
  levels:
    level-0:
      max-members: 6
      max-claimable-chunks: 12
      rankup:
        allowed: true
        cost: 15000
        next: level-1
    level-1:
      max-members: 15
      max-claimable-chunks: 24
      rankup:
        allowed: true
        cost: 52000
        next: level-2
    level-2:
      max-members: 24
      max-claimable-chunks: 48
      rankup:
        allowed: true
        cost: 125000
        next: level-3
    level-3:
      max-members: 30
      max-claimable-chunks: 64
      rankup:
        allowed: false
  roles:
    leader:
      id: 1
      weight: 100
      default-permissions:
        use-home: true
        set-home: true
        break-blocks: true
        place-blocks: true
        use-containers: true
        open-doors: true
        invite-players: true
        expel-players: true
        use-warps: true
        set-warps: true
        manage-players: true
        manage-roles: true
        expand-territory: true
        disband: true
    officer:
      id: 2
      weight: 75
      default-permissions:
        use-home: true
        set-home: true
        break-blocks: true
        place-blocks: true
        use-containers: true
        open-doors: true
        invite-players: true
        expel-players: false
        use-warps: true
        set-warps: true
        manage-players: true
        manage-roles: false
        expand-territory: true
        disband: false
    moderator:
      id: 3
      weight: 50
      default-permissions:
        use-home: true
        set-home: false
        break-blocks: true
        place-blocks: true
        use-containers: false
        open-doors: true
        invite-players: false
        expel-players: false
        use-warps: true
        set-warps: false
        manage-players: false
        manage-roles: false
        expand-territory: false
        disband: false
    recruit:
      id: 4
      weight: 25
      default-permissions:
        use-home: true
        set-home: false
        break-blocks: false
        place-blocks: false
        use-containers: false
        open-doors: true
        invite-players: false
        expel-players: false
        use-warps: false
        set-warps: false
        manage-players: false
        manage-roles: false
        expand-territory: false
        disband: false
  default-settings:
    creeper-explosions: true
    friendly-pvp: true
    enemy-pvp: false
    tnt-explosions: false
    enderman-grief: true

messages:
  errors:
    no-perm:
      command: "&8[&c!&8] &cNon hai accesso a questo comando."
      action: "&8[&c!&8] &cNon hai accesso a quest'azione."
    no-console: "&8[&c!&8] &cQuesto comando è solo per utenti in gioco."
  kingdoms:
    general:
      error:
        user-offline: "&8[&c!&8] &cL'utente scelto è offline o non esiste."
    creation:
      error:
        already-exists: "&8[&c!&8] &cE' già presente un regno con questo nome."
        has-a-kingdom: "&8[&c!&8] &cSei già membro di un regno."
        name-required: "&8[&c!&8] &cInserisci il nome del regno da creare."
      success:
        created: "&8[&a!&8] &aRegno &2{0}&a fondato!"
        created-broadcast: "&8[&5!!&8] &dL'utente &5{0}&d ha fondato il regno &5{1}&d."
    disband:
      error:
        not-have: "&8[&c!&8] &cNon hai nessun regno da eliminare."
        hasnt-permission: "&8[&c!&8] &cNon puoi eliminare il tuo regno."
      success:
        disbanded: "&8[&a!&8] &aRegno &2{0}&a eliminato!"
        disbanded-broadcast: "&8[&5!!&8] &dL'utente &5{0}&d ha eliminato il regno &5{1}&d."
    invites:
      success:
        started: "&8[&a!&8] &aUtente invitato con succcesso, ha 30 secondi per accettare l'invito."
      info:
        started: "&8[&e!&8] &eSei stato invitato ad entrare nel regno &6{0}&e da &6{1}&e. Hai 30 secondi per accettare con &6/kg accept&e."
        expired: "&8[&e!&8] &eInvito scaduto."
      error:
        already-have-one: "&8[&c!&8] &cL'utente che vuoi invitare fa già parte di un altro regno."
        never-invited: "&8[&c!&8] &cNon hai nessuna richiesta di invito in regni attiva, probabilmente è scaduto l'invito."
    joined:
      success: "&8[&a!&8] &aSei entrato a far parte del regno &2{0}&a."
      info: "&8[&e!&8] &eL'utente &6{0} &efa ora parte del tuo regno."
    expel:
      success:
        kicked: "&8[&a!&8] &aHai espulso con successo &2{0}&a dal tuo regno."
      info:
        kicked-you: "&8[&e!&8] &eSei stato espulso dal regno &6{0}&e."
        kicked-broadcast: "&8[&e!&8] &eL'utente &6{0} &eè stato espulso dal tuo regno."
      error:
        not-in-a-kingdom: "&8[&c!&8] &cNon fai parte di nessun regno."
        not-in-kingdom: "&8[&c!&8] &cL'utente scelto non fa parte di nessun regno."
        not-in-your-kingdom: "&8[&c!&8] &cL'utente scelto non fa parte del tuo regno."
        hasnt-permission: "&8[&c!&8] &cNel puoi espellere membri del tuo regno."
        target-is-greather-than-you: "&8[&c!&8] &cL'utente scelto ha un ruolo uguale o superiore al tuo."
    change-role:
      success:
        role-updated: "&8[&a!&8] &aRuolo impostato con successo."
      info:
        role-updated-you: "&8[&e!&8] &eIl tuo ruolo è stato impostato su &6{0}&e."
        role-updated-broadcast: "&8[&e!&8] &eIl ruolo dell'utente &6{0} &eè stato impostato su &6{1}&e."
      error:
        not-in-a-kingdom: "&8[&c!&8] &cNon fai parte di nessun regno."
        target-not-in-a-kingdom: "&8[&c!&8] &cL'utente scelto non fa parte di nessun regno."
        hasnt-permission: "&8[&c!&8] &cNon puoi modificare i ruoli dei player nel tuo regno."
        role-not-exist: "&8[&c!&8] &cIl ruolo scelto non esiste."
        not-in-your-kingdom: "&8[&c!&8] &cL'utente scelto non fa parte del tuo regno."
        target-player-higher-than-you: "&8[&c!&8] &cNon puoi cambiare il ruolo agli utenti con grado superiore o uguale al tuo."
        target-role-higher-than-your: "&8[&c!&8] &cNon puoi impostare o togliere un ruolo superiore o uguale al tuo ad un altro membro del tuo regno."
    claims:
      success:
        claimed: "&8[&a!&8] &aChunk inserito nel territorio del tuo regno."
        unclaimed: "&8[&a!&8] &aChunk rimosso dal territorio del tuo regno."
      info:
        territory-expanded: "&8[&e!&8] &eTerritorio del regno espanso. Mondo: &6{0}&e, x: &6{1}&e, z: &6{2}&e, X: &6{3}&e, Z: &6{4}&e."
        territory-released: "&8[&e!&8] &eTerritorio del regno rilasciato. Mondo: &6{0}&e, x: &6{1}&e, z: &6{2}&e, X: &6{3}&e, Z: &6{4}&e."
      error:
        not-in-a-kingdom: "&8[&c!&8] &cNon fai parte di nessun regno."
        hasnt-permission: "&8[&c!&8] &cIl tuo regno non permette che tu ottenga territori."
        max-claims-reached: "&8[&c!&8] &cMassimo di claim raggiunto, se possibile aumenta l'oro del tuo regno per farlo salire di livello."
        claim-not-found: "&8[&c!&8] &cClaim non trovato."
        claim-already-exist: "&8[&c!&8] &cC'è già un claim in quel chunk."
        isnt-your-kingdom: "&8[&c!&8] &cNon puoi togliere i claim di un altro regno."

helps:
  commands:
    kingdoms:
      - "&5-/kg accept &7- &5Accetti l'invito in un regno."
      - "&5-/kg disband &7- &5Elimini il tuo regno."
      - "&5-/kg claim &7- &5Ottieni un chunk 16x16 di territorio per il tuo regno."
      - "&5-/kg unclaim &7- &5Rilasci un chunk 16x16 di territorio del tuo regno."
      - "&5-/kg create &d<nome> &7- &5Crei un regno."
      - "&5-/kg invite &d<nome> &7- &5Inviti una persona nel tuo regno."
      - "&5-/kg expel &d<nome> &7- &5Espelli una persona dal tuo regno."
      - "&5-/kg changerole &d<nomeplayer> <nomeruolo> &7- &5Imposti un ruolo ad un utente del tuo regno."

placeholders:
  kingdom-level:
    placeholder: user_kingdom_level # Placeholder: %ukingdoms_user_kingdom_level%
    return-format: "&d{0}"
  kingdom-next-level:
    placeholder: user_kingdom_next_level # Placeholder: %ukingdoms_user_kingdom_next_level%
    return-format: "&d{0}"
  kingdom-gold-amount:
    placeholder: user_kingdom_gold_amount # Placeholder: %ukingdoms_user_kingdom_gold_amount%
    return-format: "&e🧈 &7{0}"
  kingdom-gold-amount-formatted:
    placeholder: user_kingdom_gold_amount_formatted # Placeholder: %ukingdoms_user_kingdom_gold_amount_formatted%
    return-format: "&e🧈 &7{0}"
  kingdom-nextrankup-cost:
    placeholder: user_kingdom_nextrankup_cost # Placeholder: %ukingdoms_user_kingdom_nextrankup_cost%
    return-format: "&e🧈 &7{0}"
  kingdom-nextrankup-cost-formatted:
    placeholder: user_kingdom_nextrankup_cost-formatted # Placeholder: %ukingdoms_user_kingdom_nextrankup_cost-formatted%
    return-format: "&e🧈 &7{0}"

permissions:
  commands:
    kingdoms:
      main: kingdoms.use
      create: kingdoms.use
      disband: kingdoms.use
      invite: kingdoms.use
      accept: kingdoms.use
      expel: kingdoms.use
      change-role: kingdoms.use
      claim: kingdoms.use
      unclaim: kingdoms.use