storage:
  type: sqlite
  credentials:
    host: "127.0.0.1"
    port: 3306
    username: ""
    password: ""
    dbname: ""
    options: ""

kingdoms:
  levels:
    level-0:
      can-rank-up: true
      max-members: 6